default:
  http_metas:
    content-type: text/html

  metas:
    title:        Asterisell
    robots:       noindex, nofollow
    description:  Asterisell project
    keywords:     asterisell, asterisk, symfony
    language:     en

  stylesheets:    [asterisell]

  javascripts:    [ ]

  has_layout:     on
  layout:         asterisell_layout
#  components:
#    headerInfo:   [login, user]


# all:
#  components:
#    headerInfo: [login, user]
